from __future__ import annotations

import logging
import os
import re
import sys
import threading
from pathlib import Path
from typing import Optional

import yaml
from justapk import APKDownloader

logger = logging.getLogger(__name__)

PACKAGE_NAME_RE = re.compile(
    r"^[A-Za-z][A-Za-z0-9_]*(?:\.[A-Za-z][A-Za-z0-9_]*)+$"
)
_QUIET_OUTPUT = threading.local()
_QUIET_STDERR = None


class _JustapkQuietStderr:
    """Filter justapk's direct progress output without hiding crawler logs."""

    def __init__(self, target):
        self.target = target

    def write(self, data: str) -> int:
        if not getattr(_QUIET_OUTPUT, "enabled", False):
            return self.target.write(data)

        lines = data.splitlines(keepends=True)
        filtered = "".join(
            line
            for line in lines
            if not line.lstrip("\r").startswith(("Trying ", "[", "  "))
        )
        if filtered:
            self.target.write(filtered)
        return len(data)

    def flush(self) -> None:
        self.target.flush()

    def __getattr__(self, name):
        return getattr(self.target, name)


def _configure_quiet_output(config: dict) -> None:
    global _QUIET_STDERR
    if not config.get("quiet", False) or isinstance(sys.stderr, _JustapkQuietStderr):
        return
    _QUIET_STDERR = _JustapkQuietStderr(sys.stderr)
    sys.stderr = _QUIET_STDERR


class _SafeOutputDir:
    """Restrict filenames generated by third-party source adapters to one directory."""

    def __init__(self, path: Path):
        self.path = path

    def mkdir(self, *args, **kwargs):
        return self.path.mkdir(*args, **kwargs)

    def __truediv__(self, filename: str) -> Path:
        safe_name = Path(str(filename).replace("\\", "/")).name
        if not safe_name or safe_name in {".", ".."}:
            raise ValueError("Source returned an invalid output filename")
        return self.path / safe_name


def load_config(config_path: str = "config.yaml") -> dict:
    path = Path(config_path)
    if not path.is_absolute() and config_path == "config.yaml":
        path = Path(__file__).with_name(config_path)
    with path.open() as f:
        return yaml.safe_load(f)


def _configure_proxy(config: dict) -> None:
    proxy = config.get("proxy", {})
    if not proxy.get("enabled", False):
        return
    scheme = proxy.get("scheme", "socks5")
    host = proxy.get("host", "127.0.0.1")
    port = proxy.get("port", 1080)
    proxy_url = f"{scheme}://{host}:{port}"
    os.environ["ALL_PROXY"] = proxy_url
    os.environ["HTTP_PROXY"] = proxy_url
    os.environ["HTTPS_PROXY"] = proxy_url
    os.environ["all_proxy"] = proxy_url
    os.environ["http_proxy"] = proxy_url
    os.environ["https_proxy"] = proxy_url
    logger.info("Proxy configured: %s", proxy_url)


def _configure_downloader_proxy(downloader: APKDownloader, config: dict) -> None:
    """Make justapk sessions use the configured proxy, not inherited settings."""
    proxy = config.get("proxy", {})
    enabled = proxy.get("enabled", False)
    proxy_url = None
    if enabled:
        proxy_url = (
            f"{proxy.get('scheme', 'socks5')}://{proxy.get('host', '127.0.0.1')}"
            f":{proxy.get('port', 1080)}"
        )

    for source in getattr(downloader, "_sources", {}).values():
        session = getattr(source, "session", None)
        if session is None:
            continue
        session.trust_env = False
        session.proxies = {"http": proxy_url, "https": proxy_url} if proxy_url else {}


def _configure_timeouts(config: dict) -> None:
    """Apply the configured per-source timeout to justapk's request helpers."""
    timeout = config.get("crawler", {}).get("per_source_timeout", 30)
    try:
        import importlib
        import justapk.utils as justapk_utils

        justapk_utils.HTTP_TIMEOUT = timeout
        for source_name in config.get("source_order", []):
            try:
                module = importlib.import_module(f"justapk.sources.{source_name}")
            except ImportError:
                continue
            if module is not None and hasattr(module, "HTTP_TIMEOUT"):
                module.HTTP_TIMEOUT = timeout
    except ImportError:
        logger.debug("Could not configure justapk timeout", exc_info=True)


def download(
    package_name: str,
    output_dir: Optional[Path] = None,
    config: Optional[dict] = None,
) -> Optional[Path]:
    if not isinstance(package_name, str) or not PACKAGE_NAME_RE.fullmatch(package_name):
        logger.warning("Invalid package name: '%s'", package_name)
        return None

    if config is None:
        config = load_config()

    if output_dir is None:
        output_dir = Path(config.get("apk_cache_dir", "apk_cache"))
    output_dir = Path(output_dir)

    _configure_proxy(config)
    _configure_timeouts(config)
    _configure_quiet_output(config)

    source_order = config.get("source_order")
    sources = source_order if source_order else None

    dl = APKDownloader(sources=sources, auto_convert_xapk=True)
    _configure_downloader_proxy(dl, config)
    _QUIET_OUTPUT.enabled = config.get("quiet", False)
    try:
        logger.info("Downloading %s ...", package_name)
        output_dir.mkdir(parents=True, exist_ok=True)
        result = dl.download(package_name, output_dir=_SafeOutputDir(output_dir))
        if result and result.path:
            result_path = Path(result.path)
            try:
                result_path.resolve().relative_to(output_dir.resolve())
            except ValueError:
                logger.error("Downloader returned a path outside output directory: %s", result_path)
                return None
            if not config.get("quiet", False):
                logger.info(
                    "Downloaded %s -> %s (%.1f MB)",
                    package_name,
                    result_path,
                    result.size / 1e6,
                )
            return result_path
        return None
    except Exception as e:
        log = logger.debug if config.get("quiet", False) else logger.warning
        log("Failed to download %s: %s", package_name, e)
        return None
    finally:
        _QUIET_OUTPUT.enabled = False


def get_app_info(
    package_name: str,
    config: Optional[dict] = None,
) -> Optional[dict]:
    if not package_name or not package_name.strip():
        return None

    if config is None:
        config = load_config()

    _configure_proxy(config)
    _configure_timeouts(config)
    _configure_quiet_output(config)

    dl = APKDownloader(sources=config.get("source_order"), auto_convert_xapk=True)
    _configure_downloader_proxy(dl, config)
    _QUIET_OUTPUT.enabled = config.get("quiet", False)
    try:
        info = dl.info(package_name)
        if info:
            return {
                "package_name": info.package,
                "app_name": info.name,
                "version": info.version,
                "icon_url": getattr(info, "icon_url", None),
                "source": info.source,
            }
        return None
    except Exception as e:
        logger.debug("Info lookup failed for %s: %s", package_name, e)
        return None
    finally:
        _QUIET_OUTPUT.enabled = False
